// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Donator_Remove_CreateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Donator_Remove_CreateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202104100911302_Donator_Remove_CreateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
